/*
 * File: app/view/HomeView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CuidaBelem.view.HomeView', {
    extend: 'Ext.Container',
    xtype: 'homeView',
    id: 'homeView',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        id: 'homeView',

        layout: {
            pack: 'start',
            type: 'vbox',
            align: 'center'
        },

        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Cuida Belém',
                items: [
                    {
                        xtype: 'button',
                        icon: 'true',
                        iconCls: 'settings',
                        text: '',
                        handler: function() {
                            Ext.Viewport.toggleMenu('left');
                        }
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                //docked: 'bottom',
                height: '100%',
                width: '100%',
                items: [
                    {
                        id: 'listSolicitacoes',
                        xtype: 'list',
                        title: 'Solicitações',
                        iconCls: 'more',
                        store: 'ServicosStore',
                        width: '100%',
                        itemTpl: [
                            '<table>',
                                '<tr>',
                                    '<td><img src="{dsImagem}"></td>',
                                    '<td style="padding-left: 10px">{nmServico} <br/> <span style="font-size: 12px;">{dsServico}</span></td>',
                                '</tr>',
                            '</table>'
                        ],
                        ui: 'round',
                        emptyText: 'Nenhum Serviço Disponível'
                    },
                    {
                        xtype: 'map',
                        title: 'Últimas Solicitações',
                        iconCls: 'locate'
                    },
                    {
                        xtype: 'list',
                        title: 'Minhas Solicitações',
                        iconCls: 'info',
                        data: [
                            {
                                name: 'Sinal de Trânsito',
                                description: 'Reparo em sinal de trânsito com defeito',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Iluminação Pública',
                                description: 'Reparo de lâmpada apagada, piscando ou acessa durante o dia',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Buraco nas vias',
                                description: 'Reparo de buraco na pista/rua, na calçada ou na ciclovia',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Dengue',
                                description: 'Vistoria em possíveis focos de Dengue',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Poda/Retirada de Árvore',
                                description: 'Pode e retirada de árvores em logradouro público',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Desobstrução de bueiros',
                                description: 'Limpeza de bueiros e galerias de águas pluviais',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Estacionamento Irregular',
                                description: 'Fiscalização de Veículos estacionados em locais públicos',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Ocupação Irregular',
                                description: 'Fiscalização do uso irregular de áreas públicas',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Remoção de entulho',
                                description: 'Remoção gratuita de entulho e objetos inservíveis de residências',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Limpeza Urbana',
                                description: 'Limpeza de resíduos deixados no logradouro',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            },
                            {
                                name: 'Outros',
                                description: 'Para outras solicitações',
                                data: '24/01/2014',
                                protocolo: '00034523'
                            }
                        ],
                        itemTpl: [
                            '<div>',
                            '    <span style="font-size: 12px;">{data}</span> <span style="font-size: 12px;">Protocolo Nº: {protocolo}</span>   <br />',
                            '    {name} <br/>',
                            '    <span style="font-size: 12px;">{description}</span>',
                            '</div>'
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Rede Social',
                        iconCls: 'team',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'label',
                                html: '<span style="font-size: 25px">Divulgue</span>',
                                margin: '0 0 20px 0'
                            },
                            {
                                xtype: 'button',
                                margin: '0 0 15px 0',
                                width: '50%',
                                text: 'Facebook'
                            },
                            {
                                xtype: 'button',
                                margin: '0 0 15px 0',
                                width: '50%',
                                text: 'Twiiter'
                            },
                            {
                                xtype: 'button',
                                width: '50%',
                                text: 'Google+'
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'bottom',
                    scrollable: false,
                    layout: {
                        pack: 'justify',
                        type: 'hbox'
                    }
                }
            }
        ]
    },

    doSetHidden : function(hidden) {
        this.callParent(arguments);

        if(hidden) {
            Ext.Viewport.removeMenu('left');
        } else {
            Ext.Viewport.setMenu(this.menuForSide('left'), {
                side: 'left',
                reveal: true
            });
        }
    },

    menuForSide : function(side) {
        var menus = [
            {
                id: 'btMeusDados',
                text: 'Meus Dados',
                scope: this,
                iconCls: 'user'
            },
            {
                id: 'btComoUsar',
                text: 'Como Usar',
                scope: this,
                iconCls: 'settings'
            },
            {
                id: 'btSobre',
                text: 'Sobre',
                scope: this,
                iconCls: 'info'
            }
        ];

        return Ext.create('Ext.Menu', { items : menus });
    }

});