/*
 * File: app/view/HomeView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CuidaBelem.view.HomeView', {
    extend: 'Ext.Container',
    xtype: 'homeView',
    id: 'homeView',

    requires: [
        'Ext.XTemplate'
    ],

    config: {

        layout: {
            pack: 'start',
            type: 'vbox',
            align: 'center'
        },

        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Cuida Belém',
                items: [
                    {
                        xtype: 'button',
                        icon: 'true',
                        iconCls: 'settings',
                        text: '',
                        handler: function() {
                            Ext.Viewport.toggleMenu('left');
                        }
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                //docked: 'bottom',
                height: '100%',
                width: '100%',
                items: [
                    {
                        id: 'listSolicitacoes',
                        xtype: 'list',
                        title: 'Solicitações',
                        iconCls: 'more',
                        store: 'ServicosStore',
                        width: '100%',
                        itemTpl: [
                            '<table>',
                                '<tr>',
                                    '<td><img src="{dsImagem}"></td>',
                                    '<td style="padding-left: 10px">{nmServico} <br/> <span style="font-size: 12px;">{dsServico}</span></td>',
                                '</tr>',
                            '</table>'
                        ],
                        ui: 'round',
                        emptyText: 'Nenhum Serviço Disponível'
                    },
                    {
                        id : 'ultimasSolicitacoesMap',
                        xtype: 'map',
                        title: 'Últimas Solicitações',
                        iconCls: 'locate',
                        mapOptions : {
                            zoom : 12,
                            //center : new google.maps.LatLng(-1.45515, -48.48271)
                            center : new google.maps.LatLng(-1.30362, -48.54348)
                        }
                    },
                    {
                        xtype: 'list',
                        id: 'listaMinhasSolicitacoes',
                        title: 'Minhas Solicitações',
                        iconCls: 'info',
                        store: 'MinhasSolicitacoesStore',
                        itemTpl: [
                            '<div>',
                            '    <span style="font-size: 12px;">{dtAberturaProcesso}</span> <span style="font-size: 12px;">Processo Nº: {nrProcesso}/ {nrAno}</span>   <br />',
                            '    {nmServico} <br/>',
                            '    <span style="font-size: 12px;">{dsServico}</span>',
                            '</div>'
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Rede Social',
                        iconCls: 'team',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'vbox'
                        },
                        items: [
                            {
                                html: '<div style="font-size: 25px; text-align: center;">Convide seus amigos para Cuidar de Belém como você!</div>',
                                margin: '0 0 20px 0',
                                width: '90%'
                            },
                            {
                                xtype: 'button',
                                margin: '0 0 15px 0',
                                width: '50%',
                                text: 'Compartilhar',
                                handler : function(){
                                    Ext.Viewport.mask({ xtype: 'loadmask', message: "Carregando..." });
                                    window.plugins.socialsharing.available(function(isAvailable) {
                                        Ext.Viewport.unmask();
                                        if (isAvailable) {
                                            window.plugins.socialsharing.share('Conheça o aplicativo Cuida Belém e ajude a Cuidar de Belém você também.', 'Cuida Belém', 'http://ww3.belem.pa.gov.br/www/wp-content/uploads/logo-prefeitura.png', 'http://www.belem.pa.gov.br/cuidabelem', function(){}, function(e) { alert("Não foi possível Compartilhar."); });
                                        }
                                    });
                                }
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'bottom',
                    scrollable: false,
                    id:'homeTabbar',
                    layout: {
                        pack: 'justify',
                        type: 'hbox'
                    }
                }
            }
        ]
    },

    doSetHidden : function(hidden) {
        this.callParent(arguments);

        if(hidden) {
            Ext.Viewport.removeMenu('left');
        } else {
            Ext.Viewport.setMenu(this.menuForSide('left'), {
                side: 'left',
                reveal: true
            });
        }
    },

    menuForSide : function(side) {
        var menus = [
            {
                id: 'btMeusDados',
                text: 'Meus Dados',
                scope: this,
                iconCls: 'user'
            },
            {
                id: 'btComoUsar',
                text: 'Como Usar',
                scope: this,
                iconCls: 'settings'
            },
            {
                id: 'btSobre',
                text: 'Sobre',
                scope: this,
                iconCls: 'info'
            }
        ];

        return Ext.create('Ext.Menu', { items : menus });
    }

});