/*
 * File: app/view/HomeView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CuidaBelem.view.MapaView', {
    extend: 'Ext.Container',
    xtype: 'mapaView',
    id: 'mapaView',

    config: {

        marcador : null,

        layout: {
            pack: 'start',
            type: 'vbox',
            align: 'center'
        },

        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Cuida Belém',
                items: [
                    {
                        id: 'btVoltarMapa',
                        xtype: 'button',
                        ui: 'back',
                        text: 'Voltar'
                    }
                ]
            },
            {
                html :'<input id="tfBuscaMapa" class="controls">'
            },
            {
                xtype: 'map',
                width: '100%',
                height : '100%',
                mapOptions : {
                    zoom : 18
                }
            },
            {
                id : 'btSalvarMapa',
                xtype : 'button',
                text: 'Salvar',
                ui : 'confirm',
                docked : 'bottom',
                disabled : true
            }
        ]
    },

    alterarCoordenadas : function(latitude, longitude) {
        var _this = this;
        var mapObj = this.down('map');
        var gMap = mapObj.getMap();
        var latLng = new google.maps.LatLng(latitude, longitude);

        if(this.getMarcador() != null) {
            this.getMarcador().setPosition(latLng);
        } else {
            this.setMarcador(new google.maps.Marker({
                position: latLng,
                animation: google.maps.Animation.DROP,
                map: gMap
            }));
        }
        //cria uma tarefa com delay
        var task = Ext.create('Ext.util.DelayedTask', function() {
            gMap.setCenter(latLng);
            _this.desabilitarBotao(false);
        });

        task.delay(1000);
    },

    desabilitarBotao : function(flag) {
        var button = this.down('button');
        button.setDisabled(flag);
    }
});