/*
 * File: app/view/IndentificacaoView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CuidaBelem.view.MeusDadosView', {
    extend: 'Ext.Panel',
    xtype: 'meusDadosView',
    id: 'meusDadosView',

    config: {
        layout: {
            align: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Meus Dados',
                items: [
                    {
                        id: 'btVoltarMeusDados',
                        xtype: 'button',
                        ui: 'back',
                        text: 'Voltar'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                width: '95%',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Nome',
                        labelAlign: 'top'
                    },
                    {
                        xtype: 'numberfield',
                        label: 'Telefone',
                        labelAlign: 'top'
                    },
                    {
                        xtype: 'emailfield',
                        label: 'E-mail',
                        labelAlign: 'top',
                        placeHolder: 'email@exemplo.com.br'
                    }
                ]
            },
            {
                xtype: 'button',
                ui: 'confirm',
                width: '95%',
                text: 'Salvar'
            }
        ]
    }

});