/*
 * File: app/view/SolicitacaoView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CuidaBelem.view.SolicitacaoView', {
    extend: 'Ext.Panel',
    xtype: 'solicitacaoView',
    id: 'solicitacaoView',

    requires: [
        'Ext.MessageBox',
        'Ext.ActionSheet'
    ],

    config: {
        id: 'solicitacaoView',

        layout: {
            align: 'center',
            type: 'vbox'
        },

        items: [
            {
                xtype: 'fieldset',
                width: '95%',
                id: 'idSolicitacaoFieldset',
                items: [
                    {
                        xtype: 'textareafield',
                        label: 'Endereço',
                        labelAlign: 'top',
                        placeHolder: 'Informe o endereço ou clique no botão Localizar para buscar no mapa',
                        itemId: 'endereco'
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'cdTipoProcesso'
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'latitude'
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'longitude'
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Nova Solicitação',
                items: [
                    {
                        id: 'btVoltarSolicitacao',
                        xtype: 'button',
                        ui: 'back',
                        text: 'Voltar'
                    }
                ]
            },
            {
                xtype: 'container',
                width: '95%',
                layout: {
                    align: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        id : 'btMapaSolicitacao',
                        xtype: 'button',
                        margin: '',
                        width: '49%',
                        text: 'Localizar'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        margin: '',
                        width: '49%',
                        model : false,
                        text: 'Anexar Foto',
                        handler : function() {
                            var items = [
                                {
                                    id : 'btTirarFoto',
                                    text : 'Tirar Foto'
                                },
                                {
                                    id : 'btFotoGaleria',
                                    text : 'Escolher Existente'
                                },
                                {
                                    text : 'Cancelar',
                                    ui : 'decline',
                                    scope : this,

                                    handler : function() {
                                        this.actions.hide();
                                    }
                                }
                            ];

                            if(!this.actions) {
                                this.actions = Ext.create('Ext.ActionSheet', {
                                    items : items
                                });
                            }

                            Ext.Viewport.add(this.actions);
                            this.actions.show();
                        }
                    }
                ]
            },
            {
                xtype: 'fieldset',
                width: '95%',
                id: 'formSolicitacaoInstrucao',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'textareafield',
                        height: '120px',
                        label: 'Descrição',
                        labelAlign: 'top',
                        itemId: 'instrucao'
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'foto'
                    }
                ]
            },
            {
                xtype: 'button',
                ui: 'confirm',
                id: 'btSalvarSolicitacao',
                width: '95%',
                text: 'Enviar'
            }
        ]
    },

    setCdTipoProcesso: function(cdTipoProcesso){
        var formSolicitacao = Ext.ComponentQuery.query("#idSolicitacaoFieldset")[0];
        formSolicitacao.down("#cdTipoProcesso").setValue(cdTipoProcesso);
    },

    alterarCoordenadas : function(latitude, longitude) {
        var formSolicitacao = Ext.ComponentQuery.query("#idSolicitacaoFieldset")[0];
        formSolicitacao.down("#latitude").setValue(latitude);
        formSolicitacao.down("#longitude").setValue(longitude);
    },

    setFoto : function(textoFoto){
        var formSolicitacao = Ext.ComponentQuery.query("#formSolicitacaoInstrucao")[0];
        formSolicitacao.down("#foto").setValue(textoFoto);
    }

});